Data fetching and processing from HERE map intermodular-routing API
apanjain/Travel-Cost-API pull request #3
Opened 2021-02-28 15:20 UTC by frappelatte28

2021-02-28 16:13 UTC, apanjain requested changes

2021-02-28 16:13 UTC, apanjain commented on views/travelData.js
> +      alternatives: 0,
Set the upper limit of alternatives to 10. Because in the end we'll be comparing all the possible travel options.

2021-02-28 16:13 UTC, apanjain commented on views/travelData.js
> +    let result = formatData(response.data.routes[0]);
Return an array of all possible travel options.

2021-02-28 16:13 UTC, apanjain commented on views/travelData.js
> +  let timeTravelled = moment
```suggestion
  let travelTime = moment
```

2021-03-01 06:18 UTC, apanjain requested changes

2021-03-01 06:18 UTC, apanjain commented on views/travelData.js
> +      res.send(result);
Put the response outside for loop.

2021-03-01 06:21 UTC, frappelatte28 commented on views/travelData.js
> +      res.send(result);
My bad! 
Done..

2021-03-01 06:37 UTC, apanjain requested changes

2021-03-01 06:37 UTC, apanjain commented on views/travelData.js
>      for (var i = 0; i <= response.data.routes.length; i++) {
remove the equal to sign, it goes out of bounds and throws error

2021-03-01 06:37 UTC, apanjain commented on views/travelData.js
>        result[i] = formatData(response.data.routes[i]);
```suggestion
result = [...result, formatData(response.data.routes[i])]; 
```
Avoid mutations

2021-03-01 06:41 UTC, apanjain commented on views/travelData.js
>        result[i] = formatData(response.data.routes[i]);
@frappelatte28 Also update .env.sample

2021-03-01 06:43 UTC, apanjain commented on views/travelData.js
>        result[i] = formatData(response.data.routes[i]);
Add mode of transport as well, to distinguish between different travel options

2021-03-23 11:00 UTC, merged